sequenceDiagram
    participant browser
    participant server
    
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: The HTTP 201 Created successful response 
    Note right of browser: The browser sends the new note to the server and gets the response that 'new note created successfully'.
    Note right of browser:  The page is not reloaded but the browser javascript code adds the new note to the list.
    deactivate server
    
    